server:
  port: 8080

spring:
  profiles:
    active: ${PROFILE_VALUE}
  application:
    name: neo-bank-deposit
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db
    validate-on-migrate: true

logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /swagger
  swagger-ui:
    path: /swagger-ui.html