spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://app-db/test_db}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}
    hikari:
      schema: products-manager
  flyway:
    schemas: products-manager
    user: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}